// Solana Breakpoint 2025 Videos Database
// YouTube Playlist: https://www.youtube.com/playlist?list=PLilwLeBwGuK4dz_gqiiDA3GfS094Yr46b

var videosData = [
  // INSTITUTIONAL & FINANCE
  { id: "yOgLKAwney0", title: "ADGM Registration Authority Welcome (His Excellency Rashed Abdulkarim Al Blooshi)", category: "institutional", companies: ["ADGM Registration Authority"], speakers: ["Rashed Abdulkarim Al Blooshi"] },
  { id: "zwkvyjwZ1o0", title: "Fireside: Galaxy's Mike Novogratz", category: "institutional", companies: ["Galaxy"], speakers: ["Mike Novogratz"] },
  { id: "Tf-vmWFxBAQ", title: "Product Keynote: Baillie Gifford (Theo Golden)", category: "institutional", companies: ["Baillie Gifford"], speakers: ["Theo Golden"] },
  { id: "XReBNJqUSbI", title: "Keynote: EXPAAM's Raoul Pal", category: "institutional", companies: ["EXPAAM"], speakers: ["Raoul Pal"] },
  { id: "9kJpRfkZIg4", title: "Opening Keynote & Macro Teach-In: EXPAAM (Raoul Pal)", category: "institutional", companies: ["EXPAAM"], speakers: ["Raoul Pal"] },
  { id: "O1tEwKC7ZGU", title: "Income Generating Strategies in Crypto: Re7 Capital (Evgeny Gokhberg)", category: "institutional", companies: ["Re7 Capital"], speakers: ["Evgeny Gokhberg"] },
  { id: "0_0Dl_vOgYc", title: "Product Keynote: SkyBridge Capital (Anthony Scaramucci)", category: "institutional", companies: ["SkyBridge Capital"], speakers: ["Anthony Scaramucci"] },
  { id: "2fCjxpb5y7g", title: "How to Allocate to Digital Assets: EXPAAM (Pierre Henry)", category: "institutional", companies: ["EXPAAM"], speakers: ["Pierre Henry"] },
  { id: "8t3JLQYTgmo", title: "Generating Alpha: Venture Strategies Within the Solana Ecosystem", category: "institutional", companies: [], speakers: [] },
  { id: "4eYRheV1obY", title: "Generating Alpha: The Digital Asset Hedge Fund Landscape", category: "institutional", companies: [], speakers: [] },
  { id: "L3hndG_h5bU", title: "The Institutional Case for Solana: Multicoin Capital (Kyle Samani)", category: "institutional", companies: ["Multicoin Capital"], speakers: ["Kyle Samani"] },
  { id: "Pxhy5q9QMBU", title: "Bullish on Solana: Bullish (Michael Lau)", category: "institutional", companies: ["Bullish"], speakers: ["Michael Lau"] },
  { id: "9OOvhIqkwXk", title: "Simplified ETF Access for Solana: Bitwise (Matthew Hougan)", category: "institutional", companies: ["Bitwise"], speakers: ["Matthew Hougan"] },
  { id: "D-kJvIJ0uBo", title: "Institutional-Grade Staking in ETFs with Helius and Bitwise", category: "institutional", companies: ["Helius", "Bitwise"], speakers: [] },
  { id: "QsX-3D5P7fE", title: "Fireside: Paxos' Chad Cascarilla", category: "institutional", companies: ["Paxos"], speakers: ["Chad Cascarilla"] },
  { id: "WlJCP9vISMI", title: "Fireside: Circle's Jeremy Allaire and Kristin Smith", category: "institutional", companies: ["Circle"], speakers: ["Jeremy Allaire", "Kristin Smith"] },
  { id: "gB-rs__T_5g", title: "Fireside: Anchorage Digital (Sergio Mello)", category: "institutional", companies: ["Anchorage Digital"], speakers: ["Sergio Mello"] },
  { id: "_FepLUqalwE", title: "An Institutional Perspective: DBS (Evy Theunis)", category: "institutional", companies: ["DBS"], speakers: ["Evy Theunis"] },
  { id: "rH7LUklyI6k", title: "Product Keynote: Singapore Gulf Bank (Justin Peyton)", category: "institutional", companies: ["Singapore Gulf Bank"], speakers: ["Justin Peyton"] },
  { id: "VHnWNuMIgP4", title: "An Allocator's View: Fireside With a Major European Bank", category: "institutional", companies: [], speakers: [] },
  { id: "6ka_gm4Vhp4", title: "The Case for Permanent Capital Vehicles: Anagram (Joe Eagan)", category: "institutional", companies: ["Anagram"], speakers: ["Joe Eagan"] },
  { id: "95OW8BnjvKM", title: "Fireside: Ripple Labs' Luke Judges", category: "institutional", companies: ["Ripple Labs"], speakers: ["Luke Judges"] },
  { id: "luDSUNrbH5c", title: "Fireside: JPMorgan's Scott Lucas", category: "institutional", companies: ["JPMorgan"], speakers: ["Scott Lucas"] },
  { id: "I8BQdJH_pbg", title: "Keynote: Galaxy (Michael Marcantonio)", category: "institutional", companies: ["Galaxy"], speakers: ["Michael Marcantonio"] },
  { id: "wXEXlRgtsYk", title: "Product Keynote: Astana International Finance Centre", category: "institutional", companies: ["Astana International Finance Centre"], speakers: [] },
  { id: "HkA6nSlNZ_o", title: "Product Keynote: DK Bank (Yudong Zheng)", category: "institutional", companies: ["DK Bank"], speakers: ["Yudong Zheng"] },
  { id: "ECmDMrgFr18", title: "Keynote: Anchorage (Prasanna Gautam)", category: "institutional", companies: ["Anchorage"], speakers: ["Prasanna Gautam"] },
  { id: "gGeIy2w_VWU", title: "DATs: Why DATs Will Succeed — and Why They Won't", category: "institutional", companies: [], speakers: [] },

  
  // DEFI
    { id: "r8IRNGU5CZE", title: "Keynote: Jupiter (Kash Dhanda)", category: "defi", companies: ["Jupiter"], speakers: ["Kash Dhanda"] },
  { id: "h1bkUoS61R8", title: "The State of Returns on Solana: Solstice (Ben Nadareski)", category: "defi", companies: ["Solstice"], speakers: ["Ben Nadareski"] },
  { id: "dr2u6NS3WoT", title: "The State of Revenue on Solana: Blockworks (Dan Smith)", category: "defi", companies: ["Blockworks"], speakers: ["Dan Smith"] },
  { id: "R1mgFWtaaqI", title: "Product Keynote: Backed Finance (Adam Levit)", category: "defi", companies: ["Backed Finance"], speakers: ["Adam Levit"] },
  { id: "oiWxp5J2Nws", title: "This House rejects derivative-based models that tokenize equities", category: "defi", companies: [], speakers: [] },
  { id: "I_lNcgA6mLo", title: "Keynote: Erebor (Suzanne Dannheim)", category: "defi", companies: ["Erebor"], speakers: ["Suzanne Dannheim"] },
  { id: "TDdWB-gFIw4", title: "This House rejects political alignment as a growth strategy for crypto", category: "defi", companies: [], speakers: [] },
  { id: "oGnSr3U4U9E", title: "One Chain to Rule Them All: Can Solana Support Wall Street's Demands?", category: "defi", companies: [], speakers: [] },
  { id: "IxCRPxp-gAw", title: "Tokenization: Where Solana's Push Stands and Where It's Going", category: "defi", companies: [], speakers: [] },
  { id: "2qTdXSK5AoQ", title: "Keynote: Jito (Lucas Bruder)", category: "defi", companies: ["Jito"], speakers: ["Lucas Bruder"] },
  { id: "c2NSIYbyq3A", title: "Product Keynote: Drift (Cindy Leow)", category: "defi", companies: ["Drift"], speakers: ["Cindy Leow"] },
  { id: "XPoayC3OmxM", title: "Kamino: The Next Chapter (Marius Ciubotariu)", category: "defi", companies: ["Kamino"], speakers: ["Marius Ciubotariu"] },
  { id: "_lJXD6sfhIGa", title: "Keynote: Figure (Mike Cagney)", category: "defi", companies: ["Figure"], speakers: ["Mike Cagney"] },
  { id: "pXXc47BQUvE", title: "The True Price: How Pyth Is Rebuilding the $50B Industry", category: "defi", companies: ["Pyth"], speakers: [] },
  { id: "O0VYopeDMhk", title: "Keynote: DFlow (Milesh Math)", category: "defi", companies: ["DFlow"], speakers: ["Milesh Math"] }{ id: "rL92uVQdFyQ", title: "Sharpening Your Trading Edge: Titan (Chris Chung)", category: "defi", companies: ["Titan"], speakers: ["Chris Chung"] },
  { id: "HluHxelkEgk", title: "Ranger: Building a Unified Market (FA2)", category: "defi", companies: ["Ranger"], speakers: ["FA2"] },
  { id: "0zb57hUxMmE", title: "The Future Is Borderless: deBridge (Alex Smirnov)", category: "defi", companies: ["deBridge"], speakers: ["Alex Smirnov"] },
  { id: "WWHoxNuouOM", title: "Making Finance Invisible: The Killer App for Tokenized Economy", category: "defi", companies: [], speakers: [] },
  { id: "U1MlYQt0bEs", title: "This House: Value Will Accrue to Applications Rather Than L1s", category: "defi", companies: [], speakers: [] },
  { id: "47fzkScJyDE", title: "Product Keynote: HumidiFi (Kevin Pang)", category: "defi", companies: ["HumidiFi"], speakers: ["Kevin Pang"] },
  { id: "i85nThodvHc", title: "Product Keynote: Flash Trade (Anas Khader)", category: "defi", companies: ["Flash Trade"], speakers: ["Anas Khader"] },
  { id: "aL6bC9SZU9I", title: "Project 0: The Largest DeFi Prime Broker (MacBrennan Peet)", category: "defi", companies: ["Project 0"], speakers: ["MacBrennan Peet"] },
  { id: "xiQ2BgHhEeE", title: "When Data Scientists Rewrite Price Formation: Crunch (Jean Herelle)", category: "defi", companies: ["Crunch"], speakers: ["Jean Herelle"] },
  { id: "dVvhfMf3NVY", title: "Gold Capital Markets: Oro Labs (Usman Saleem)", category: "defi", companies: ["Oro Labs"], speakers: ["Usman Saleem"] },
  { id: "irAU4z7lkCA", title: "The Metrics Gap: Net-New Metrics in Solana's Ledger", category: "defi", companies: [], speakers: [] },
  { id: "sZ7B8bm9-vY", title: "The Solana Constitution: Multicoin/Jito (Tushar Jain, Nick Almond)", category: "defi", companies: ["Multicoin", "Jito"], speakers: ["Tushar Jain", "Nick Almond"] },
  { id: "jb8_Z2auXL0", title: "The Most Delightful Way to Earn Yields: Sanctum (FP)", category: "defi", companies: ["Sanctum"], speakers: ["FP"] },
  { id: "V6a-GznG6EA", title: "Interest-Rate Swaps Unlock Next Phase: Exponent (Thomas Lefort)", category: "defi", companies: ["Exponent"], speakers: ["Thomas Lefort"] },
  { id: "XWFHrfSWQlQ", title: "Leverage Without Chaos: Turbo Tokens: Carrot (James Blair)", category: "defi", companies: ["Carrot"], speakers: ["James Blair"] },
  { id: "FaF8uORdJMo", title: "Superteam Demo Day: Asgard (Prastut Kumar)", category: "deii", companies: ["Asgard"], speakers: ["Prastut Kumar"] },
  { id: "FiRtPXGEomc", title: "Product Keynote: Glider (Brian Huang)", category: "defi", companies: ["Glider"], speakers: ["Brian Huang"] },
  { id: "tsjld4QIeLU", title: "Making Global Business Run on Solana: Squads (Stepan Simkin)", category: "defi", companies: ["Squads"], speakers: ["Stepan Simkin"] },
  { id: "Pavpk1BOvdw", title: "Superteam Demo Day: Pye (Erik Ashdown)", category: "defi", companies: ["Pye"], speakers: ["Erik Ashdown"] },
  { id: "5L_aU_1FNUs", title: "Going Public on Internet Capital Markets: Metaplex (Stephen Hess)", category: "defi", companies: ["Metaplex"], speakers: ["Stephen Hess"] },
  { id: "-97xJamwHCM", title: "Welcome to Day 2: Sanctum (Eno Sim)", category: "defi", companies: ["Sanctum"], speakers: ["Eno Sim"] },
  { id: "rAH-al0HghQ", title: "Product Keynote: Zeus Network (Justin Wang)", category: "defi", companies: ["Zeus Network"], speakers: ["Justin Wang"] },
  { id: "CLx8SvCn7e8", title: "Superteam Demo Day: Lavarage (Alexander Ho)", category: "defi", companies: ["Lavarage"], speakers: ["Alexander Ho"] },
  { id: "pMaoHEnTM2o", title: "Superteam Demo Day: Ranger Finance (FA2)", category: "defi", companies: ["Ranger Finance"], speakers: ["FA2"] },
  { id: "gmaXrEklOcE", title: "Superteam Demo Day: Atomiq Labs (Sylvia Durach)", category: "defi", companies: ["Atomiq Labs"], speakers: ["Sylvia Durach"] },
  { id: "hMGqrMYlc9M", title: "Superteam Demo Day: Darklake (Vitor Py Braga)", category: "defi", companies: ["Darklake"], speakers: ["Vitor Py Braga"] },
  { id: "uSseSMm4brM", title: "Tokenizing the Internet: Unlocking 364M Domains for DeFi Growth", category: "defi", companies: [], speakers: [] },
  
  
  // CEX
  { id: "xPkuNbt5Prs", title: "Inside the Architecture of Universal Exchange: Bitget (Gracy Chen)", category: "CEX", companies: ["Bitget"], speakers: ["Gracy Chen"] },
  { id: "MpwfiqHd6i4", title: "Fireside: Bybit's Ben Zhou", category: "CEX", companies: ["Bybit"], speakers: ["Ben Zhou"] },

  
  // INFRASTRUCTURE
  { id: "IAhGpzjZpbM", title: "What to Expect at Breakpoint 2025: Solana Foundation (Lily Liu, Akshay BD)", category: "infrastructure", companies: ["Solana Foundation"], speakers: ["Lily Liu", "Akshay BD"] },
  { id: "QdvYQbjpMj4", title: "Welcome to Day 1: Solana Foundation (Jiani Chen)", category: "infrastructure", companies: ["Solana Foundation"], speakers: ["Jiani Chen"] },
  { id: "KwrzT56VyIM", title: "The State of the Network: Anza (Brennan Watt)", category: "infrastructure", companies: ["Anza"], speakers: ["Brennan Watt"] },
  { id: "KBXjNFRnVzA", title: "Keynote: Ellipsis Labs (Eugene Chen)", category: "infrastructure", companies: ["Ellipsis Labs"], speakers: ["Eugene Chen"] },
  { id: "Wo5xNy8cEmw", title: "Keynote: Temporal (Ben Coverston)", category: "infrastructure", companies: ["Temporal"], speakers: ["Ben Coverston"] },
  { id: "dswq61yla5Q", title: "Welcome to Dev Day: Solana Foundation (Solomon Ponomarev)", category: "infrastructure", companies: ["Solana Foundation"], speakers: ["Solomon Ponomarev"] },
  { id: "O1nZh0vg1VI", title: "Tech Talk: Chorus One (Brian Crain)", category: "infrastructure", companies: ["Chorus One"], speakers: ["Brian Crain"] },
  { id: "ffIOaK4bAqk", title: "Tech Talk: SevenLabs (Kellian Vitré)", category: "infrastructure", companies: ["SevenLabs"], speakers: ["Kellian Vitré"] },
  { id: "KCXXlQd0PXI", title: "Tech Talk: Neon (Ivan Bjelajac)", category: "infrastructure", companies: ["Neon"], speakers: ["Ivan Bjelajac"] },
  { id: "6ZuUSt014wQ", title: "Tech Talk: BULK (Junaid Peer)", category: "infrastructure", companies: ["BULK"], speakers: ["Junaid Peer"] },
  { id: "T9N0Sbk7UqU", title: "Wen Firedancer", category: "infrastructure", companies: [], speakers: [] },
  { id: "L405rB-rP7A", title: "Tech Talk: Arcium (Nico Schapeler)", category: "infrastructure", companies: ["Arcium"], speakers: ["Nico Schapeler"] },
  { id: "_VPQHv5WRP4", title: "Tech Talk: Ghost (Chris Chang)", category: "infrastructure", companies: ["Ghost"], speakers: ["Chris Chang"] },
  { id: "oO-r-i_DlCg", title: "Tech Talk: Blueshift (Claire Fan)", category: "infrastructure", companies: ["Blueshift"], speakers: ["Claire Fan"] },
  { id: "4fHUqMv-y9g", title: "Anza Block (Brennan Watt)", category: "infrastructure", companies: ["Anza"], speakers: ["Brennan Watt"] },
  { id: "dLNVmnW5izQ", title: "Anza Block: Alessandro Decina", category: "infrastructure", companies: ["Anza"], speakers: ["Alessandro Decina"] },
  { id: "7kPJ0C9gYSg", title: "Anza Block: Max Resnick", category: "infrastructure", companies: ["Anza"], speakers: ["Max Resnick"] },
  { id: "eMIPEUi3oWM", title: "Anza Block: Alexander Meißner", category: "infrastructure", companies: ["Anza"], speakers: ["Alexander Meißner"] },
  { id: "0RRKrabfvZY", title: "Tech Talk: R3 Labs (Richard Brown)", category: "infrastructure", companies: ["R3 Labs"], speakers: ["Richard Brown"] },
  { id: "1SLzWDBt9iY", title: "Tech Talk: Solana Mobile / Solana Labs (Mike Mobiledev.skr)", category: "infrastructure", companies: ["Solana Mobile", "Solana Labs"], speakers: ["Mike Mobiledev.skr"] },
  { id: "7kduka4FXl0", title: "Tech Talk: Malbec Labs (Ben Marx)", category: "infrastructure", companies: ["Malbec Labs"], speakers: ["Ben Marx"] },
  { id: "PgdP0uql6U0", title: "Tech Talk: MagicBlock Labs (Andrea Fortugno)", category: "infrastructure", companies: ["MagicBlock Labs"], speakers: ["Andrea Fortugno"] },
  { id: "1ieMx4pJsng", title: "Anchor: Today and Tomorrow: OtterSec/Solana Foundation", category: "infrastructure", companies: ["OtterSec", "Solana Foundation"], speakers: [] },
  { id: "0RjtbvrKjnU", title: "Tech Talk: Switchboard (Mitchell Gildenberg)", category: "infrastructure", companies: ["Switchboard"], speakers: ["Mitchell Gildenberg"] },
  { id: "xreOFvSCgew", title: "Tech Talk: Reilabs (Marcin Kostrzewa)", category: "infrastructure", companies: ["Reilabs"], speakers: ["Marcin Kostrzewa"] },
  { id: "hQml2lIMY4w", title: "Tech Talk: Kinetic (Grant Stenger)", category: "infrastructure", companies: ["Kinetic"], speakers: ["Grant Stenger"] },
  { id: "JQTr1ezjM24", title: "Scaling the Read Layer to 1M TPS: FluxBeam (Scott Hague)", category: "infrastructure", companies: ["FluxBeam"], speakers: ["Scott Hague"] },
  { id: "SYgFyVP6FwE", title: "Tech Talk: Light Protocol (Swen Schaeferjohann)", category: "infrastructure", companies: ["Light Protocol"], speakers: ["Swen Schaeferjohann"] },
  { id: "RYnutXTpcIM", title: "Product Keynote: Blueshift (Dean Little)", category: "infrastructure", companies: ["Blueshift"], speakers: ["Dean Little"] },
  { id: "Yxjk5AuypsE", title: "Product Keynote: Helius (Nicolas Pennie)", category: "infrastructure", companies: ["Helius"], speakers: ["Nicolas Pennie"] },
  { id: "ELH2w3xf0Zw", title: "Keynote: DoubleZero (Austin Federa)", category: "infrastructure", companies: ["DoubleZero"], speakers: ["Austin Federa"] },
  { id: "fshuWyZKs7E", title: "Superteam Demo Day: Solana ID (Simon Molitor)", category: "infrastructure", companies: ["Solana ID"], speakers: ["Simon Molitor"] },
  { id: "PnlLtg5F9ZM", title: "Superteam Demo Day: GameShift (Karthik Makayee)", category: "infrastructure", companies: ["GameShift"], speakers: ["Karthik Makayee"] },
  { id: "N_MHl3CLOAk", title: "Superteam Demo Day: Xitadel (Ryot Seo)", category: "infrastructure", companies: ["Xitadel"], speakers: ["Ryot Seo"] },
  { id: "BjWVCnffZ7A", title: "Superteam Demo Day: Encifher (Rishabh Gupta)", category: "infrastucture", companies: ["Encifher"], speakers: ["Rishabh Gupta"] },
  { id: "eKVklQBW09I", title: "Solana in the Multi-Chain World by NEAR Intents (Illia Polosukhin)", category: "infrastructure", companies: ["NEAR"], speakers: ["Illia Polosukhin"] },


  // PAYMENTS
  { id: "hyi-1Ia0KNU", title: "Product Keynote: Coinbase (Sabs Sachdeva, Andrew Allen)", category: "payments", companies: ["Coinbase"], speakers: ["Sabs Sachdeva", "Andrew Allen"] },
  { id: "cTFumlE38k0", title: "Product Keynote: Wormhole (Saeed Badreg)", category: "payments", companies: ["Wormhole"], speakers: ["Saeed Badreg"] },
  { id: "XmxY33U0tJk", title: "Product Keynote: Keel (Cian Breathnach)", category: "payments", companies: ["Keel"], speakers: ["Cian Breathnach"] },
  { id: "G-_IVPccOF0", title: "Product Keynote: Crypto.com (Park Kwon)", category: "payments", companies: ["Crypto.com"], speakers: ["Park Kwon"] },
  { id: "odYcNgPxJO4", title: "Solana's Superapp Moment: Jupiter/Bitwise (Kash Dhanda, Danny Nelson)", category: "payments", companies: ["Jupiter", "Bitwise"], speakers: ["Kash Dhanda", "Danny Nelson"] },
  { id: "OFaOfGyzpPI", title: "Product Keynote: Sphere (Arnold Lee)", category: "payments", companies: ["Sphere"], speakers: ["Arnold Lee"] },
  { id: "ge8FRyYkwIU", title: "Product Keynote: OSL (Eugene Cheung)", category: "payments", companies: ["OSL"], speakers: ["Eugene Cheung"] },
  { id: "uayvgt0oyuU", title: "Product Keynote: B2C2 (Alizee Carli)", category: "payments", companies: ["B2C2"], speakers: ["Alizee Carli"] },
  { id: "VWX8vuZZW1k", title: "Product Keynote: 2WA: Metacomp (Xiaoyun Xu, Chun Kit Chu)", category: "payments", companies: ["2WA", "Metacomp"], speakers: ["Xiaoyun Xu", "Chun Kit Chu"] },
  { id: "PcyTar_mhOQ", title: "Digital Dollars for All: Zepz (Nika Naghavi)", category: "payments", companies: ["Zepz"], speakers: ["Nika Naghavi"] },
  { id: "LfAHFLI_CFM", title: "Product Keynote: CopperX (Tarun Mangukiya)", category: "payments", companies: ["CopperX"], speakers: ["Tarun Mangukiya"] },
  { id: "2j41dIkdYqA", title: "How Hardware Wallets and Multi-Chain Swaps Power ICM", category: "payments", companies: [], speakers: [] },
  { id: "JOfo4WgXjPo", title: "Product Keynote: Abra (Bill Barhydt)", category: "payments", companies: ["Abra"], speakers: ["Bill Barhydt"] },
  { id: "4InwJ45Rctg", title: "Product Keynote: Streamflow (Malisha Stanojevic)", category: "payments", companies: ["Streamflow"], speakers: ["Malisha Stanojevic"] },
  { id: "WM7-58Y9U-M", title: "Product Keynote: Tala (Nicolas Cabrera)", category: "payments", companies: ["Tala"], speakers: ["Nicolas Cabrera"] },
  { id: "KWRgAVy-AoY", title: "Product Keynote: Forma (Farhaj Mayan)", category: "payments", companies: ["Forma"], speakers: ["Farhaj Mayan"] },
  { id: "Ymfc6jZ7Gb8", title: "Product Keynote: Huma Finance (Erbil Karaman)", category: "payments", companies: ["Huma Finance"], speakers: ["Erbil Karaman"] },
  { id: "GNU6svAfQnk", title: "Superteam Demo Day: Watt Protocol (Vladimir Picha)", category: "payments", companies: ["Watt Protocol"], speakers: ["Vladimir Picha"] },
  { id: "wNYWu6yN7q8", title: "Superteam Demo Day: Xelio (João Vasco Martins)", category: "payments", companies: ["Xelio"], speakers: ["João Vasco Martins"] },
  { id: "vYuZUNPJzqA", title: "Product Keynote: KAST (Raagulan Pathy)", category: "payments", companies: ["KAST"], speakers: ["Raagulan Pathy"] },


  // AI 
  { id: "GegcZPaN3xc", title: "Private Verifiable AI in an Age of Confusion: Ambient (Travis Good)", category: "ai", companies: ["Ambient"], speakers: ["Travis Good"] },
  { id: "XyYcU_GQWv0", title: "Perle Labs Creator: The Frontline of Human-Led AI (Ahmed Rashad)", category: "ai", companies: ["Perle Labs"], speakers: ["Ahmed Rashad"] },
  { id: "y2JLwcM-prU", title: "Product Keynote: SendAI (Yash Agarwal)", category: "ai", companies: ["SendAI"], speakers: ["Yash Agarwal"] },
  { id: "xaGlz5IV2zI", title: "Superteam Demo Day: Latinum.ai (Brendan Regan)", category: "ai", companies: ["Latinum.ai"], speakers: ["Brendan Regan"] },
  { id: "Tzou_utR5KQ", title: "Product Keynote: ShardLab (Jaewook Lee)", category: "ai", companies: ["ShardLab"], speakers: ["Jaewook Lee"] },
  { id: "IY_-oMrO0r4", title: "Product Keynote: Neuko (Austin Hurwitz)", category: "ai", companies: ["Neuko"], speakers: ["Austin Hurwitz"] },
  { id: "j6J4UPC327I", title: "Superteam Demo Day: Cleopetra (Umang Verma)", category: "defi", companies: ["Cleopetra"], speakers: ["Umang Verma"] },

  // DATA
  { id: "xnTnOEDshN4", title: "Product Keynote: Dune (Alessandro Losi)", category: "data", companies: ["data"], speakers: ["Alessandro Losi"] },
  { id: "dBiokmJZw7o", title: "Product Keynote: Nansen (Charlie Kavanagh)", category: "data", companies: ["Nansen"], speakers: ["Charlie Kavanagh"] },
  { id: "p4QnEx29Quw", title: "Product Keynote: Birdeye (Kha Nguyen)", category: "data", companies: ["Birdeye"], speakers: ["Kha Nguyen"] },
  { id: "VNLcKdUyVk0", title: "Product Keynote: Artemis (Jon Ma)", category: "data", companies: ["Artemis"], speakers: ["Jon Ma"] },
  { id: "LOvv_ADUgjk", title: "What Wall Street Wants: Metrics That Matter: Artemis (Jon Ma)", category: "data", companies: ["Artemis"], speakers: ["Jon Ma"] },

  // CREDIT & RWA
  { id: "g7dMXmc7GB8", title: "Product Keynote: Solflare (Filip Dragoslavic)", category: "credit", companies: ["Solflare"], speakers: ["Filip Dragoslavic"] },
  { id: "r7qI5l3wXbE", title: "Lightspeed: Solana's Investor Relations Hub: Blockworks (Dan Smith)", category: "credit", companies: ["Lightspeed", "Blockworks"], speakers: ["Dan Smith"] },
  { id: "163WVyqTvKxgzY", title: "The Future of Tokenized Funds: How Institutional Asset Managers Scale Onchain", category: "credit", companies: [], speakers: [] },
  { id: "j_Y38wyhWcg", title: "The UAE: The New Wall Street of Digital Finance: Solmate (Marco Santori)", category: "credit", companies: ["Solmate"], speakers: ["Marco Santori"] },
  { id: "Q1dpZI5MJY4", title: "Product Keynote: Layer33: Marinade Finance (Nicky Scannella)", category: "credit", companies: ["Layer33", "Marinade Finance"], speakers: ["Nicky Scannella"] },
  { id: "QIUZ50F02DU", title: "Keynote: Solflare (Vidor Gencel)", category: "credit", companies: ["Solflare"], speakers: ["Vidor Gencel"] },
  { id: "8tNIkNAQU4s", title: "BAXUS 2.0: Real-World Applications, Not Just RWA (Carrie Kellar)", category: "credit", companies: ["BAXUS"], speakers: ["Carrie Kellar"] },
  { id: "IY_-oMrO0r4", title: "Product Keynote: Neuko (Austin Hurwitz)", category: "credit", companies: ["Neuko"], speakers: ["Austin Hurwitz"] },
  { id: "GqwdEhFEWAE", title: "Product Keynote: Moonbirds (Spencer Gordon-Sand)", category: "credit", companies: ["Moonbirds"], speakers: ["Spencer Gordon-Sand"] },
  { id: "oDje-KV8XT4", title: "NFT Ticketing Doesn't Work: KYD Labs (Ahmed Nimale)", category: "credit", companies: ["KYD Labs"], speakers: ["Ahmed Nimale"] },
  { id: "W7u8vRHU-u0", title: "Product Keynote: Worm (Nass Diba)", category: "credit", companies: ["Worm"], speakers: ["Nass Diba"] },
  { id: "-JLUo_rnOQc", title: "Product Keynote: Byreal (Emily Bao)", category: "RWA", companies: ["Byreal"], speakers: ["Emily Bao"] },
  { id: "FiRtPXGEomc", title: "Product Keynote: Glider (Brian Huang)", category: "credit", companies: ["Glider"], speakers: ["Brian Huang"] },
  { id: "-JLUo_rnOQc", title: "Product Keynote: Byreal (Emily Bao)", category: "RWA", companies: ["Byreal"], speakers: ["Emily Bao"] },
  { id: "6J4BupINCus", title: "Superteam Demo Day: Fundl (Josip Volarević)", category: "rwa", companies: ["Fundl"], speakers: ["Josip Volarević"] },


  // SECURITY
  { id: "8ErcjKccnOc", title: "Security Block: Neodyme (Sebastian Fritsch)", category: "security", companies: ["Neodyme"], speakers: ["Sebastian Fritsch"] },
  { id: "wp6pRX4kaFQ", title: "Security Block: Asymmetric Research (Felix Wilhelm)", category: "security", companies: ["Asymmetric Research"], speakers: ["Felix Wilhelm"] },
  { id: "DOyXoeEc9fs", title: "Security Block: Almanax (Francesco Piccoli)", category: "security", companies: ["Almanax"], speakers: ["Francesco Piccoli"] },
  { id: "j8BMKFQQPWY", title: "Security Block: Certora (Pamina Georgiev)", category: "security", companies: ["Certora"], speakers: ["Pamina Georgiev"] },
  { id: "OEpw-087JUU", title: "Product Keynote: Raise (George Bousis)", category: "security", companies: ["Raise"], speakers: ["George Bousis"] },
  { id: "ntnjwsrgxVg", title: "Keynote: Arcium (Yannik Schrade)", category: "security", companies: ["Arcium"], speakers: ["Yannik Schrade"] },
  { id: "6KNDG_i_2uk", title: "The China Opportunity: Solana Company (Joseph Chee)", category: "security", companies: ["Solana Company"], speakers: ["Joseph Chee"] },
  { id: "DvJdmVLCYpA", title: "Kompass: Ensuring SPL-Token Stays Safe on Pinocchio (Daniel Cumming)", category: "security", companies: ["Kompass"], speakers: ["Daniel Cumming"] },

  // Mobile
  { id: "MvC8L-Z-2Tc", title: "Update From Solana Mobile: Seeker Economy (Emmett Hollyer)", category: "mobile", companies: ["Solana Mobile"], speakers: ["Emmett Hollyer"] },

  // VC
  { id: "wGj-J__CoCQ", title: "Product Keynote: 6th Man Ventures (Mike Dudas)", category: "vc", companies: ["6th Man Ventures"], speakers: ["Mike Dudas"] },
  { id: "B_vC8WOGXKk", title: "Product Keynote: Electric Capital (Ren CF)", category: "vc", companies: ["Electric Capital"], speakers: ["Ren CF"] },
  { id: "f65eS-vrhs4", title: "Product Keynote: RockawayX (Adam Bilko)", category: "vc", companies: ["RockawayX"], speakers: ["Adam Bilko"] },
  { id: "VDt3NO5PQ9k", title: "Fireside: Animoca's Yat Siu", category: "vc", companies: ["Animoca"], speakers: ["Yat Siu"] },


// DePin 
  { id: "x8ZXrvQEukY", title: "Product Keynote: Helium (Abhay Kumar)", category: "depin", companies: ["Helium"], speakers: ["Abhay Kumar"] },
  { id: "N8TCYuz8Buk", title: "Product Keynote: Wingbits (Robin Wingardh)", category: "depin", companies: ["Wingbits"], speakers: ["Robin Wingardh"] },
  { id: "GXKQYsd_IK8", title: "Product Keynote: Render Network Foundation (Sunny Osahn)", category: "depin", companies: ["Render Network Foundation"], speakers: ["Sunny Osahn"] },
  { id: "SnVvKZp9arY", title: "Superteam Demo Day: DeCharge (Prakash Kamaraj)", category: "depin", companies: ["DeCharge"], speakers: ["Prakash Kamaraj"] },
  { id: "JJAxc01OwUo", title: "Superteam Demo Day: Tapedrive (Zelimir Fedoran)", category: "DePin", companies: ["Tapedrive"], speakers: ["Zelimir Fedoran"] },
  { id: "8FuzRFamMRw", title: "Mapping the Real World With Solana: Hivemapper (Ariel Seidman)", category: "depin", companies: ["Hivemapper"], speakers: ["Ariel Seidman"] },

// Prediction Markets 
  { id: "9sHmn6P7DQA", title: "Product Keynote: Kalshi (John Wang)", category: "prediction markets", companies: ["Kalshi"], speakers: ["John Wang"] },
  { id: "W7u8vRHU-u0", title: "Product Keynote: Worm (Nass Diba)", category: "prediction markets", companies: ["Worm"], speakers: ["Nass Diba"] },
  { id: "7HgDAw6WUPE", title: "Superteam Demo Day: Trepa (Jong-Chan Chung)", category: "prediction markets", companies: ["Trepa"], speakers: ["Jong-Chan Chung"] },
  { id: "OPvk9DRi_cM", title: "Superteam Demo Day: Triad Markets (Davi Cardoso)", category: "prediction markets", companies: ["Triad Markets"], speakers: ["Davi Cardoso"] },

// NFT & Gaming  & Consumer
  { id: "oDje-KV8XT4", title: "NFT Ticketing Doesn't Work: KYD Labs (Ahmed Nimale)", category: "nft/gaming/consumer", companies: ["KYD Labs"], speakers: ["Ahmed Nimale"] },
  { id: "GqwdEhFEWAE", title: "Product Keynote: Moonbirds (Spencer Gordon-Sand)", category: "nft/gaming", companies: ["Moonbirds"], speakers: ["Spencer Gordon-Sand"] },
  { id: "ozctdCBDrdM", title: "Superteam Demo Day: CHOMP (Kiko Zang)", category: "gaming", companies: ["CHOMP"], speakers: ["Kiko Zang"] },
  { id: "N7a45QoJAIo", title: "Superteam Demo Day: MetEngine (Harsh Prashant Ghodkar)", category: "gaming", companies: ["MetEngine"], speakers: ["Harsh Prashant Ghodkar"] },
  { id: "Vx-wkw4zZnw", title: "Superteam Demo Day: Crypto Fantasy League (Jonas Aditya Sunandar)", category: "gaming", companies: ["Crypto Fantasy League"], speakers: ["Jonas Aditya Sunandar"] },
  { id: "Vx-wkw4zZnw", title: "Superteam Demo Day: Crypto Fantasy League (Jonas Aditya Sunandar)", category: "nft/gaming/consumer", companies: ["Crypto Fantasy League"], speakers: ["Jonas Aditya Sunandar"] },
  { id: "HZ9WIWe4pFE", title: "Sorare x Solana: Sports, Crypto, Collecting (Nicolas Julia)", category: "nft/gaming/consumer", companies: ["Sorare"], speakers: ["Nicolas Julia"] },


 // Fundraising 
  { id: "PtIAXNDy_UE", title: "Product Keynote: Seedplex (Treggs)", category: "fundraising", companies: ["Seedplex"], speakers: ["Treggs"] },
  { id: "E1fyJD5tyio", title: "Legion and Solana: Positioned for Onchain IPOs (Matt O'Connor)", category: "fundraising", companies: ["Legion"], speakers: ["Matt O'Connor"] },
  { id: "B_-bh-CWgiE", title: "Product Keynote: MetaDAO (Proph3t)", category: "fundraising", companies: ["MetaDAO"], speakers: ["Proph3t"] },

// Wallets 
  { id: "ADghebANEDE", title: "Building Your Financial Life Onchain: Phantom (Brandon Millman)", category: "wallets", companies: ["Phantom"], speakers: ["Brandon Millman"] },
  { id: "zJRUPue-pq0", title: "Swig: The Future of Smart Wallets on Solana (Justin Blumenthal)", category: "wallets", companies: ["Swig"], speakers: ["Justin Blumenthal"] },
  { id: "sdcu_Glm7EY", title: "Fireside: Backpack's Armani Ferrante", category: "wallet", companies: ["Backpack"], speakers: ["Armani Ferrante"] },
  { id: "XKiqqYw03GM", title: "Product Keynote: Ledger (Ian Rogers)", category: "wallets", companies: ["Ledger"], speakers: ["Ian Rogers"] },

// COMMUNITY & EVENTS
  { id: "PSbUK-JK9LM", title: "Product Keynote: Meridian (Benedict Brady)", category: "community", companies: ["Meridian"], speakers: ["Benedict Brady"] },
  { id: "AVLy87mlHIQ", title: "Celebrating the Next Generation of Builders and Creators", category: "community", companies: [], speakers: [] },
  { id: "pcFw6RPpJNs", title: "This House believes that Solana culture is cooked", category: "community", companies: [], speakers: [] },
  { id: "g68-Lus7428", title: "Community Awards: Bangerz & Solflare (quicks)", category: "community", companies: ["Bangerz", "Solflare"], speakers: ["quicks"] },
  { id: "S9NwK_J10oo", title: "See You at Breakpoint 2026: Solana Foundation (Dan Albert)", category: "community", companies: ["Solana Foundation"], speakers: ["Dan Albert"] },
  { id: "iSg1bBa3uRs", title: "Winners of the Colosseum Cypherpunk Hackathon", category: "community", companies: [], speakers: [] },
  { id: "oiV5hqC04yE", title: "Welcome to Community Day: Superteam (Aditya Shetty, Anh Tran)", category: "community", companies: ["Superteam"], speakers: ["Aditya Shetty", "Anh Tran"] },
  { id: "THA1z8Zsi2c", title: "Solana Incubator: Grow Your Company (Emon Motamedi)", category: "community", companies: ["Solana Incubator"], speakers: ["Emon Motamedi"] },
  { id: "hZhJSBbJBn0", title: "Solana Founders: What We Care About Now", category: "community", companies: [], speakers: [] },
  { id: "C_0vpvBtkGw", title: "This House: Token Buybacks Are Net-Negative Value Accrual", category: "community", companies: [], speakers: [] },
  { id: "MBImX7g1J0w", title: "Normies Shouldn't Have To Deal: The Hidden Costs of Janky UX (Caitlin Cook)", category: "community", companies: [], speakers: ["Caitlin Cook"] },
  { id: "jEYqGLKaRlg", title: "Welcome to Day 3: Solana Foundation (Rebekka Revel)", category: "community", companies: ["Solana Foundation"], speakers: ["Rebekka Revel"] },

];

