// Solana Breakpoint 2025 Videos Database
// YouTube Playlist: https://www.youtube.com/playlist?list=PLilwLeBwGuK4dz_gqiiDA3GfS094Yr46b

const videosData = [
  // INSTITUTIONAL & FINANCE
  { id: "yOgLKAwney0", title: "ADGM Registration Authority Welcome (His Excellency Rashed Abdulkarim Al Blooshi)", category: "institutional" },
  { id: "zwkvyjwZ1o0", title: "Fireside: Galaxy's Mike Novogratz", category: "institutional" },
  { id: "Tf-vmWFxBAQ", title: "Product Keynote: Baillie Gifford (Theo Golden)", category: "institutional" },
  { id: "XReBNJqUSbI", title: "Keynote: EXPAAM's Raoul Pal", category: "institutional" },
  { id: "9kJpRfkZIg4", title: "Opening Keynote & Macro Teach-In: EXPAAM (Raoul Pal)", category: "institutional" },
  { id: "O1tEwKC7ZGU", title: "Income Generating Strategies in Crypto: Re7 Capital (Evgeny Gokhberg)", category: "institutional" },
  { id: "0_0Dl_vOgYc", title: "Product Keynote: SkyBridge Capital (Anthony Scaramucci)", category: "institutional" },
  { id: "2fCjxpb5y7g", title: "How to Allocate to Digital Assets: EXPAAM (Pierre Henry)", category: "institutional" },
  { id: "8t3JLQYTgmo", title: "Generating Alpha: Venture Strategies Within the Solana Ecosystem", category: "institutional" },
  { id: "4eYRheV1obY", title: "Generating Alpha: The Digital Asset Hedge Fund Landscape", category: "institutional" },
  { id: "L3hndG_h5bU", title: "The Institutional Case for Solana: Multicoin Capital (Kyle Samani)", category: "institutional" },
  { id: "Pxhy5q9QMBU", title: "Bullish on Solana: Bullish (Michael Lau)", category: "institutional" },
  { id: "9OOvhIqkwXk", title: "Simplified ETF Access for Solana: Bitwise (Matthew Hougan)", category: "institutional" },
  { id: "D-kJvIJ0uBo", title: "Institutional-Grade Staking in ETFs with Helius and Bitwise", category: "institutional" },
  { id: "QsX-3D5P7fE", title: "Fireside: Paxos' Chad Cascarilla", category: "institutional" },
  { id: "WlJCP9vISMI", title: "Fireside: Circle's Jeremy Allaire and Kristin Smith", category: "institutional" },
  { id: "gB-rs__T_5g", title: "Fireside: Anchorage Digital (Sergio Mello)", category: "institutional" },
  { id: "_FepLUqalwE", title: "An Institutional Perspective: DBS (Evy Theunis)", category: "institutional" },
  { id: "rH7LUklyI6k", title: "Product Keynote: Singapore Gulf Bank (Justin Peyton)", category: "institutional" },
  { id: "VHnWNuMIgP4", title: "An Allocator's View: Fireside With a Major European Bank", category: "institutional" },
  { id: "6ka_gm4Vhp4", title: "The Case for Permanent Capital Vehicles: Anagram (Joe Eagan)", category: "institutional" },
  { id: "95OW8BnjvKM", title: "Fireside: Ripple Labs' Luke Judges", category: "institutional" },
  { id: "luDSUNrbH5c", title: "Fireside: JPMorgan's Scott Lucas", category: "institutional" },
  { id: "MpwfiqHd6i4", title: "Fireside: Bybit's Ben Zhou", category: "institutional" },
  { id: "I8BQdJH_pbg", title: "Keynote: Galaxy (Michael Marcantonio)", category: "institutional" },
  { id: "wXEXlRgtsYk", title: "Product Keynote: Astana International Finance Centre", category: "institutional" },
  { id: "HkA6nSlNZ_o", title: "Product Keynote: DK Bank (Yudong Zheng)", category: "institutional" },
  { id: "ECmDMrgFr18", title: "Keynote: Anchorage (Prasanna Gautam)", category: "institutional" }
  
  // DEFI
  { id: "r8lRNGU5CZE", title: "Keynote: Jupiter (Kash Dhanda)", category: "defi" },
  { id: "hibkUoS6lR8", title: "The State of Returns on Solana: Solstice (Ben Nadareski)", category: "defi" },
  { id: "dr2u6NS3WoI", title: "The State of Revenue on Solana: Blockworks (Dan Smith)", category: "defi" },
  { id: "RimgFWtaaqI", title: "Product Keynote: Backed Finance (Adam Levi)", category: "defi" },
  { id: "oiWxp5J2Nws", title: "This House rejects derivative-based models that tokenize equities", category: "defi" },
  { id: "LOvv_ADUgjk", title: "What Wall Street Wants: Metrics That Matter: Artemis (Jon Ma)", category: "defi" },
  { id: "I_hNcgA6mLo", title: "Keynote: Erebor (Suzanne Dannheim)", category: "defi" },
  { id: "TD0WB-gFIw4", title: "This House rejects political alignment as a growth strategy for crypto", category: "defi" },
  { id: "oGnSr3U4U9E", title: "One Chain to Rule Them All: Can Solana Support Wall Street's Demands?", category: "defi" },
  { id: "IxCRPxp-gAw", title: "Tokenization: Where Solana's Push Stands and Where It's Going", category: "defi" },
  { id: "2gTdXSKSAOQ", title: "Keynote: Jito (Lucas Bruder)", category: "defi" },
  { id: "ELH2w3xf0Zw", title: "Keynote: DoubleZero (Austin Federa)", category: "defi" },
  { id: "c2NSIYbyq3A", title: "Product Keynote: Drift (Cindy Leow)", category: "defi" },
  { id: "XPoayC3OmKM", title: "Kamino: The Next Chapter (Marius Ciubotariu)", category: "defi" },
  { id: "_UXD6sfhH9s", title: "Keynote: Figure (Mike Cagney)", category: "defi" },
  { id: "pXXc47BQUvE", title: "The True Price: How Pyth Is Rebuilding the $50B Industry", category: "defi" },
  { id: "O0VYopeDMhk", title: "Keynote: DFlow (Nitesh Nath)", category: "defi" },
  { id: "rL92uVQdFyQ", title: "Sharpening Your Trading Edge: Titan (Chris Chung)", category: "defi" },
  { id: "HluHxelkEgk", title: "Ranger: Building a Unified Market (FA2)", category: "defi" },
  { id: "0zb57hUxMmE", title: "The Future Is Borderless: deBridge (Alex Smirnov)", category: "defi" },
  { id: "B_-bh-CWgiE", title: "Product Keynote: MetaDAO (Proph3t)", category: "defi" },
  { id: "WWHoxNuouOM", title: "Making Finance Invisible: The Killer App for Tokenized Economy", category: "defi" },
  { id: "U1MlYQt0bEs", title: "This House: Value Will Accrue to Applications Rather Than L1s", category: "defi" },
  { id: "47fzkScJyDE", title: "Product Keynote: HumidiFi (Kevin Pang)", category: "defi" },
  { id: "i85nThodvHc", title: "Product Keynote: Flash Trade (Anas Khader)", category: "defi" },
  { id: "aL6bC9SZU9I", title: "Project 0: The Largest DeFi Prime Broker (MacBrennan Peet)", category: "defi" },
  { id: "xiQ2BgHhEeE", title: "When Data Scientists Rewrite Price Formation: Crunch (Jean Herelle)", category: "defi" },
  { id: "dVvhfMf3NVY", title: "Gold Capital Markets: Oro Labs (Usman Saleem)", category: "defi" },
  { id: "irAU4z7lkCA", title: "The Metrics Gap: Net-New Metrics in Solana's Ledger", category: "defi" },
  { id: "sZ7B8bm9-vY", title: "The Solana Constitution: Multicoin/Jito (Tushar Jain, Nick Almond)", category: "defi" },
  { id: "jb8_Z2auXL0", title: "The Most Delightful Way to Earn Yields: Sanctum (FP)", category: "defi" },
  { id: "V6a-GznG6EA", title: "Interest-Rate Swaps Unlock Next Phase: Exponent (Thomas Lefort)", category: "defi" },
  { id: "XWFHrfSWQlQ", title: "Leverage Without Chaos: Turbo Tokens: Carrot (James Blair)", category: "defi" }
];

